version: '3.9'

services:
  rdbms:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_MULTIPLE_DATABASES: catalg_dev,catalg_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 55551:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/rdbms:/docker-entrypoint-initdb.d
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command:
      - air
      - -c
      - air.toml
    depends_on:
      - rdbms
    environment:
      APP_ENV: development
      DATABASE_HOST: rdbms
      DATABASE_NAME: catalg_dev
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DOCKER: 'true'
      PASSWORD_PEPPER: 'dev environment pepper'
      PORT: 8080
    ports:
      - '55550:8080'
    tty: true
    volumes:
      - './server:/go/github.com/bensaufley/catalg/server'
      - /go/github.com/bensaufley/catalg/server/tmp
  start_rdbms:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rdbms
    command:
      - rdbms:5432
volumes:
  pgdata:
