// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateUserParams struct {
	UUID        string  `json:"uuid"`
	Username    *string `json:"username"`
	Email       *string `json:"email"`
	NewPassword *string `json:"newPassword"`
	Password    string  `json:"password"`
}
