#!/bin/bash -e

cd "$(dirname "$0")/.."

script/update

selected_app="$(echo "${1:-all}" | tr '[:upper:]' '[:lower:]')"

if [ "$selected_app" = "all" ] || [ "$selected_app" = "server" ]; then
  docker-compose run --rm start_rdbms
  docker-compose run \
    -e APP_ENV=test \
    --rm \
    server \
    go test \
      -race \
      -covermode atomic \
      -coverprofile cover.out \
      ./...
fi
